ALTER TABLE counters ADD COLUMN input_tokens INTEGER NOT NULL DEFAULT 0;
ALTER TABLE counters ADD COLUMN cached_input_tokens INTEGER NOT NULL DEFAULT 0;
ALTER TABLE counters ADD COLUMN output_tokens INTEGER NOT NULL DEFAULT 0;
ALTER TABLE counters ADD COLUMN total_tokens INTEGER NOT NULL DEFAULT 0;
ALTER TABLE counters ADD COLUMN usage_reports INTEGER NOT NULL DEFAULT 0;
